// Data for the 7 Cloud Native service pages. Reuses the AiService shape and is
// rendered by the shared ServiceDetail (via CloudServiceDetail). Cloud proof is
// real: LuxeLocker, PropMetrics, MultiUnitX and ShiftERP all run on AWS.

import {
  Cloud, Server, GitBranch, Container, ShieldCheck, Settings, RefreshCw,
  ArrowRightLeft, Gauge, TrendingUp, Lock, Zap, Layers, Workflow, Database,
  Network, Activity, Boxes, Repeat, Rocket, Search, Eye, Scale, Wrench,
  KeyRound, FileCheck, Globe, DollarSign, Clock, Target, Cpu,
} from "lucide-react";
import type { AiService } from "@/lib/ai-services";

export const cloudServices: AiService[] = [
  // 1 — CLOUD NATIVE JOURNEY
  {
    slug: "cloud-native-journey",
    name: "Cloud Native Journey",
    navLabel: "Cloud Native Journey",
    pill: "Cloud Native Journey",
    headline: "Your end-to-end cloud native transformation, engineered.",
    subhead:
      "From first cloud strategy to a fully cloud-native platform — containers, automation, and managed infrastructure on AWS, GCP, or Azure, delivered by engineers who run it in production.",
    accent: "from-sky-50 via-white to-brand-50",
    heroVariant: "modular",
    metaTitle: "Cloud Native Transformation Services UK | Tackxel",
    metaDescription:
      "End-to-end cloud native transformation. Containers, CI/CD, and managed infrastructure on AWS, GCP & Azure — engineered for scale by a senior UK team. Book a call.",
    keywords: [
      "cloud native transformation",
      "cloud native journey",
      "cloud native consulting UK",
      "cloud transformation services",
      "cloud native development company",
    ],
    overviewHeading: "What is a cloud native journey?",
    overview: [
      "A cloud native journey is the end-to-end process of moving how you build and run software toward the cloud's strengths: containers, automation, elastic scale, and managed services. It's bigger than \"move servers to AWS\" — it's adopting the architecture, tooling, and practices that let a small team operate reliable, scalable systems without a data centre or a 24/7 ops department.",
      "We take you through the whole journey: assessing where you are, designing a target cloud-native architecture, containerising and automating, and standing up the infrastructure-as-code, CI/CD, and observability that make it operable. Whether you're greenfield or modernising, we sequence the work so you get value early and aren't forced into a risky big-bang cutover.",
      "Because we run cloud-native systems in production for real clients — auto-scaling AWS platforms with containers, managed databases, and automated pipelines — our recommendations are grounded in operating reality, not reference diagrams. You finish with a platform your team can actually run, plus the practices to keep evolving it.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We map your current architecture, workloads, and team — and define what cloud-native should mean for you specifically." },
      { no: "02", title: "Design", desc: "A target architecture: containers, networking, data, scaling, and the managed services that remove undifferentiated heavy lifting." },
      { no: "03", title: "Build", desc: "Infrastructure-as-code, containerisation, CI/CD, and observability stood up incrementally — value early, not big-bang." },
      { no: "04", title: "Migrate", desc: "Workloads moved in slices with rollback paths, so nothing critical depends on a single cutover." },
      { no: "05", title: "Operate", desc: "Runbooks, monitoring, cost controls, and knowledge transfer so your team owns the platform confidently." },
    ],
    benefitsHeading: "Why go cloud native",
    benefits: [
      { Icon: Gauge, title: "Elastic scale", desc: "Handle 10x traffic without re-architecting — infrastructure that grows and shrinks with demand." },
      { Icon: Zap, title: "Ship faster", desc: "Automated pipelines and containers mean changes go from commit to production in minutes, safely." },
      { Icon: DollarSign, title: "Pay for what you use", desc: "Right-sized, auto-scaling infrastructure and managed services keep cloud spend proportional to value." },
      { Icon: ShieldCheck, title: "Reliable by design", desc: "Self-healing, multi-AZ infrastructure and observability built in from day one." },
      { Icon: Wrench, title: "Less ops burden", desc: "Managed services and automation free your team from babysitting servers." },
      { Icon: Repeat, title: "Repeatable & versioned", desc: "Infrastructure-as-code means environments are reproducible, reviewable, and rollback-able." },
    ],
    useCasesHeading: "What a cloud native journey delivers",
    useCases: [
      { Icon: Container, title: "Containerised platform", desc: "Your apps packaged in Docker and run on a consistent, portable runtime." },
      { Icon: Layers, title: "Infrastructure-as-code", desc: "Your whole environment defined in Terraform — reproducible and reviewable." },
      { Icon: Workflow, title: "Automated delivery", desc: "CI/CD pipelines from commit to production with safe, repeatable releases." },
      { Icon: Activity, title: "Observability", desc: "Metrics, logs, and alerts so you can see and trust what's happening in production." },
      { Icon: Gauge, title: "Auto-scaling services", desc: "Compute that scales to load, like the auto-scaling AWS behind ShiftERP." },
      { Icon: Cloud, title: "Multi-cloud foundations", desc: "Architecture that fits AWS, GCP, or Azure to your needs and constraints." },
    ],
    tech: [
      { name: "AWS", sub: "EC2/S3/RDS" },
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "Docker", sub: "Containers" },
      { name: "Terraform", sub: "IaC" },
      { name: "GitHub Actions", sub: "CI/CD" },
      { name: "AWS ECS", sub: "Containers" },
      { name: "CloudWatch", sub: "Observability" },
      { name: "GCP", sub: "Cloud" },
      { name: "Azure", sub: "Cloud" },
    ],
    why: [
      "We don't just advise on cloud — we run it. Our shipped platforms live on AWS today: LuxeLocker (native apps + IoT on EC2, S3, and RDS, Dockerized with CI/CD), PropMetrics (AWS with CloudWatch observability), MultiUnitX (AWS with CloudFront), and ShiftERP (auto-scaling EC2, ECS, ALB, and RDS PostgreSQL).",
      "That production experience is the difference between a cloud-native plan that looks good on a slide and one your team can actually operate. Senior engineers, real systems, 11+ products shipped.",
    ],
    faqs: [
      { q: "Do we have to go all-in at once?", a: "No. We sequence the journey so you get value early and migrate in slices with rollback paths — never a risky big-bang cutover." },
      { q: "AWS, GCP, or Azure — which should we use?", a: "Whichever fits your team, workloads, and constraints. We're not tied to one provider; most of our production work runs on AWS, but we design for the right fit." },
      { q: "Do we need Kubernetes?", a: "Not always. For many teams, managed container services (like AWS ECS) are simpler and cheaper to run. We recommend Kubernetes only when the complexity genuinely earns it." },
      { q: "Will this reduce our cloud bill?", a: "Usually, yes — right-sizing, auto-scaling, and managed services cut waste. We build cost monitoring in so spend stays proportional to value." },
      { q: "Can our team operate it afterwards?", a: "That's the goal. We deliver infrastructure-as-code, runbooks, observability, and knowledge transfer so your team owns the platform — no lock-in to us." },
      { q: "Greenfield or existing systems?", a: "Both. We build cloud-native from scratch and modernise existing systems onto cloud-native foundations." },
    ],
  },

  // 2 — DEVOPS & PLATFORM ENGINEERING
  {
    slug: "devops-platform-engineering",
    name: "DevOps & Platform Engineering",
    navLabel: "DevOps & Platform Engineering",
    pill: "DevOps & Platform Engineering",
    headline: "CI/CD and platform engineering that lets you ship every day.",
    subhead:
      "Automated pipelines, infrastructure-as-code, and internal platforms that turn slow, risky releases into fast, boring ones. The DevOps foundations behind software that ships continuously.",
    accent: "from-brand-100/70 via-white to-sky-50",
    heroVariant: "workflow",
    metaTitle: "DevOps & Platform Engineering Services UK | Tackxel",
    metaDescription:
      "DevOps & platform engineering: CI/CD pipelines, infrastructure-as-code, and automation that make releases fast and safe. Senior UK engineers. Book a call.",
    keywords: [
      "DevOps services UK",
      "platform engineering services",
      "CI/CD pipeline development",
      "DevOps consulting UK",
      "infrastructure automation",
    ],
    overviewHeading: "What is DevOps & platform engineering?",
    overview: [
      "DevOps is the practice of automating and streamlining how software goes from a developer's commit to running in production — builds, tests, deployments, and the infrastructure underneath. Platform engineering takes it further: building the internal tooling and \"paved roads\" that let every engineer ship safely without becoming an infrastructure expert.",
      "We design and build the pipelines and platforms that make shipping fast and unremarkable: CI/CD with automated testing and one-click (or zero-click) deploys, infrastructure-as-code so environments are reproducible, secrets and config managed properly, and observability so you catch problems before users do. The result is a team that releases daily with confidence instead of dreading deploy day.",
      "This is foundational work we do on every production system we ship. ShiftERP runs on GitHub Actions CI/CD into auto-scaling AWS; our mobile and web platforms ship through automated pipelines to stores and the web. We bring those same battle-tested DevOps foundations to your stack.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We review how you build, test, and deploy today, and where the friction and risk actually are." },
      { no: "02", title: "Design", desc: "A pipeline and platform design: branching, environments, automated gates, and infrastructure-as-code." },
      { no: "03", title: "Build", desc: "CI/CD pipelines, IaC, secrets management, and the automation that removes manual release steps." },
      { no: "04", title: "Harden", desc: "Observability, alerting, rollback, and the guardrails that make fast releases safe ones." },
      { no: "05", title: "Enable", desc: "Documentation and golden paths so your team ships independently, without a bottleneck." },
    ],
    benefitsHeading: "Why invest in DevOps",
    benefits: [
      { Icon: Zap, title: "Ship every day", desc: "Automated pipelines turn releases from rare, risky events into fast, routine ones." },
      { Icon: ShieldCheck, title: "Safer releases", desc: "Automated tests, gates, and rollback mean fewer incidents and faster recovery when they happen." },
      { Icon: Repeat, title: "Reproducible everything", desc: "Infrastructure-as-code makes environments consistent, reviewable, and disposable." },
      { Icon: Clock, title: "Less time firefighting", desc: "Observability and automation cut the toil that eats your engineers' weeks." },
      { Icon: TrendingUp, title: "Faster delivery", desc: "Shorter lead time from idea to production means you out-iterate the competition." },
      { Icon: Workflow, title: "Golden paths", desc: "Internal platforms let every engineer ship safely without deep infra knowledge." },
    ],
    useCasesHeading: "What we build",
    useCases: [
      { Icon: Workflow, title: "CI/CD pipelines", desc: "Automated build, test, and deploy from commit to production — like ShiftERP on GitHub Actions." },
      { Icon: Layers, title: "Infrastructure-as-code", desc: "Terraform-managed environments that are reproducible and reviewable." },
      { Icon: Activity, title: "Observability stacks", desc: "Metrics, logs, traces, and alerting wired into your services." },
      { Icon: KeyRound, title: "Secrets & config", desc: "Proper secrets management and environment configuration across stages." },
      { Icon: Container, title: "Container build systems", desc: "Reliable, cached Docker builds and registries in your pipeline." },
      { Icon: Settings, title: "Internal developer platforms", desc: "Self-service tooling and paved roads so engineers ship without friction." },
    ],
    tech: [
      { name: "GitHub Actions", sub: "CI/CD" },
      { name: "Terraform", sub: "IaC" },
      { name: "Docker", sub: "Containers" },
      { name: "AWS", sub: "Cloud" },
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "ArgoCD", sub: "GitOps" },
      { name: "CloudWatch", sub: "Monitoring" },
      { name: "Datadog", sub: "Observability" },
    ],
    why: [
      "DevOps isn't a side service for us — it's how we ship everything. ShiftERP deploys through GitHub Actions into auto-scaling AWS (EC2 Auto Scaling, ECS, ALB, RDS PostgreSQL); our mobile and web products ship through automated pipelines. We bring foundations we rely on daily, not theory.",
      "Senior engineers who've operated production systems under real load — across 11+ shipped products — building the pipelines and platforms that let your team ship with confidence.",
    ],
    faqs: [
      { q: "What's the difference between DevOps and platform engineering?", a: "DevOps automates the path from commit to production. Platform engineering builds the internal tooling and golden paths so every engineer can use that path safely without being an infra expert. They're complementary." },
      { q: "Can you work with our existing CI/CD?", a: "Yes. We improve and harden what you have as readily as we build from scratch — GitHub Actions, GitLab CI, CircleCI, and others." },
      { q: "Do we need Kubernetes for good DevOps?", a: "No. Great DevOps is about automation, testing, and observability — achievable on managed services like AWS ECS without Kubernetes' overhead. We add it only when warranted." },
      { q: "How do you make releases safe, not just fast?", a: "Automated tests and gates, staged rollouts, observability with alerting, and one-step rollback — speed and safety come from the same automation." },
      { q: "Will our team be able to maintain the pipelines?", a: "Yes — we document everything and build golden paths so your engineers ship independently, with no dependency on us." },
      { q: "How do you handle secrets and compliance?", a: "Proper secrets management, least-privilege access, and auditable infrastructure-as-code — with compliance-aware practices where your data demands it." },
    ],
  },

  // 3 — KUBERNETES CONSULTANCY
  {
    slug: "kubernetes-consultancy",
    name: "Kubernetes Consultancy",
    navLabel: "Kubernetes Consultancy",
    pill: "Kubernetes Consultancy",
    headline: "Kubernetes done right — or honest advice that you don't need it.",
    subhead:
      "Container orchestration design, cluster setup, and optimisation from engineers who'll tell you the truth about when Kubernetes is worth its complexity — and when managed containers win.",
    accent: "from-brand-50 via-white to-orange-50",
    heroVariant: "models",
    metaTitle: "Kubernetes Consultancy & Consulting Services UK | Tackxel",
    metaDescription:
      "Kubernetes consultancy UK: cluster design, setup, optimisation and migration from senior engineers — plus honest advice on when you don't need K8s. Book a call.",
    keywords: [
      "Kubernetes consultancy",
      "Kubernetes consulting UK",
      "container orchestration services",
      "Kubernetes cluster setup",
      "Kubernetes optimisation",
    ],
    overviewHeading: "What is Kubernetes consultancy?",
    overview: [
      "Kubernetes is the de facto standard for orchestrating containers at scale — running, scaling, healing, and networking your services across a cluster. It's powerful and, famously, complex. Kubernetes consultancy is about getting that power without drowning in the complexity: the right cluster design, sensible defaults, and an honest assessment of whether you need it at all.",
      "We help teams design and run Kubernetes properly: cluster architecture, networking and ingress, autoscaling, resource management, secrets, observability, and CI/CD into the cluster. We also do the unglamorous optimisation work — fixing noisy-neighbour problems, right-sizing, and taming cost — that turns a fragile cluster into a dependable platform.",
      "Crucially, we'll tell you the truth. For many teams, managed container services like AWS ECS deliver what they need with far less operational burden — and we run those in production too. We recommend Kubernetes when the scale, portability, or ecosystem genuinely earns its complexity, not because it's fashionable.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We evaluate whether Kubernetes is the right tool for you — or whether managed containers serve you better." },
      { no: "02", title: "Design", desc: "Cluster architecture: networking, ingress, autoscaling, resource limits, and multi-environment strategy." },
      { no: "03", title: "Build", desc: "Cluster setup, workload manifests/Helm, secrets, and CI/CD into the cluster with GitOps where it fits." },
      { no: "04", title: "Optimise", desc: "Right-sizing, autoscaling tuning, cost control, and reliability hardening." },
      { no: "05", title: "Operate", desc: "Observability, runbooks, and knowledge transfer so your team runs the cluster confidently." },
    ],
    benefitsHeading: "Why Kubernetes (when it fits)",
    benefits: [
      { Icon: Gauge, title: "Scale & self-healing", desc: "Automatic scaling, restarts, and rescheduling keep services up under load and failure." },
      { Icon: Globe, title: "Portability", desc: "A consistent runtime across clouds and environments reduces lock-in." },
      { Icon: Boxes, title: "Efficient packing", desc: "Run more workloads on fewer nodes with smart resource scheduling." },
      { Icon: ShieldCheck, title: "Honest scoping", desc: "We'll steer you to simpler managed containers when Kubernetes would be overkill." },
      { Icon: DollarSign, title: "Cost control", desc: "Right-sizing and autoscaling tuning stop clusters from quietly burning budget." },
      { Icon: Network, title: "Rich ecosystem", desc: "Service mesh, GitOps, and operators when you genuinely need them." },
    ],
    useCasesHeading: "What we deliver",
    useCases: [
      { Icon: Boxes, title: "Cluster design & setup", desc: "Production-ready clusters on EKS, GKE, or AKS with sensible defaults." },
      { Icon: Wrench, title: "Cluster optimisation", desc: "Fix reliability, right-size resources, and cut cost on existing clusters." },
      { Icon: Workflow, title: "GitOps delivery", desc: "Declarative, version-controlled deploys into the cluster with ArgoCD or Flux." },
      { Icon: ArrowRightLeft, title: "Migration to K8s", desc: "Move workloads onto Kubernetes safely, in slices." },
      { Icon: Activity, title: "Cluster observability", desc: "Metrics, logs, and alerting tuned for container workloads." },
      { Icon: Scale, title: "K8s vs managed review", desc: "An honest assessment of whether you should be on Kubernetes at all." },
    ],
    tech: [
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "AWS EKS", sub: "Managed K8s" },
      { name: "Helm", sub: "Packaging" },
      { name: "ArgoCD", sub: "GitOps" },
      { name: "Docker", sub: "Containers" },
      { name: "Terraform", sub: "IaC" },
      { name: "Prometheus", sub: "Metrics" },
      { name: "AWS ECS", sub: "Managed alt." },
    ],
    why: [
      "We run containers in production — including auto-scaling, multi-service AWS infrastructure behind ShiftERP (ECS, ALB, EC2 Auto Scaling). That means we know orchestration from operating it, and we'll give you the honest call on Kubernetes versus simpler managed containers.",
      "No fashion-driven complexity. Senior engineers, real systems, 11+ products shipped — recommending what you should actually run.",
    ],
    faqs: [
      { q: "Do we actually need Kubernetes?", a: "Often not — and we'll say so. Many teams are better served by managed container services like AWS ECS. We recommend Kubernetes only when scale, portability, or ecosystem needs genuinely justify the complexity." },
      { q: "Which managed Kubernetes do you use?", a: "EKS (AWS), GKE (Google), or AKS (Azure) depending on your cloud and needs. Managed control planes remove a lot of the operational burden." },
      { q: "Can you fix our existing cluster?", a: "Yes. A lot of our Kubernetes work is optimisation — reliability, right-sizing, autoscaling, and cost on clusters that have grown unwieldy." },
      { q: "How do you keep Kubernetes costs under control?", a: "Right-sizing requests/limits, autoscaling tuning, efficient bin-packing, and monitoring — clusters waste money fast without this discipline." },
      { q: "Can our team run it after you leave?", a: "Yes — we deliver manifests/Helm, GitOps, observability, runbooks, and knowledge transfer so your team operates the cluster independently." },
      { q: "Do you do GitOps?", a: "Yes — declarative, version-controlled deployments with ArgoCD or Flux, so cluster state is reviewable and reproducible." },
    ],
  },

  // 4 — SUPPLY CHAIN SECURITY
  {
    slug: "supply-chain-security",
    name: "Supply Chain Security",
    navLabel: "Supply Chain Security",
    pill: "Supply Chain Security",
    headline: "Secure your software supply chain, from commit to production.",
    subhead:
      "Lock down the build pipeline attackers actually target — dependencies, CI/CD, artifacts, and secrets — with practical controls that fit how your team already ships.",
    accent: "from-emerald-50 via-white to-brand-50",
    heroVariant: "document",
    metaTitle: "Software Supply Chain Security Services UK | Tackxel",
    metaDescription:
      "Software supply chain security: secure your dependencies, CI/CD, artifacts and secrets against pipeline attacks. Practical controls from senior engineers. Book a call.",
    keywords: [
      "software supply chain security",
      "supply chain security services",
      "CI/CD security",
      "DevSecOps UK",
      "build pipeline security",
    ],
    overviewHeading: "What is software supply chain security?",
    overview: [
      "Your software supply chain is everything that goes into shipping your product: open-source dependencies, build tools, CI/CD pipelines, container images, artifacts, and the secrets that tie it together. It's also where modern attackers increasingly aim — compromising a dependency or a pipeline is far easier than breaching a hardened production system, and the blast radius is enormous.",
      "Supply chain security is the discipline of hardening that path. We assess and lock it down end to end: dependency scanning and pinning, securing CI/CD with least-privilege and isolated runners, signing and verifying artifacts and images, managing secrets properly, and generating the SBOMs and provenance that prove what's in your software. The goal is practical, layered defence that fits how your team actually ships — not security theatre that grinds delivery to a halt.",
      "Because we build and operate CI/CD pipelines for production systems ourselves, we secure the supply chain from the inside out — we know where the real weak points are because we work in these pipelines every day.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We map your supply chain — dependencies, pipelines, artifacts, secrets — and find the real exposure." },
      { no: "02", title: "Prioritise", desc: "Risks ranked by likelihood and blast radius, so effort goes where it actually reduces danger." },
      { no: "03", title: "Harden", desc: "Dependency controls, least-privilege CI/CD, artifact signing, and secrets management put in place." },
      { no: "04", title: "Verify", desc: "SBOMs, provenance, and automated scanning wired into the pipeline so security is continuous." },
      { no: "05", title: "Sustain", desc: "Policies, alerts, and runbooks so the chain stays secure as dependencies and pipelines evolve." },
    ],
    benefitsHeading: "Why secure your supply chain",
    benefits: [
      { Icon: ShieldCheck, title: "Close the easy door", desc: "Pipelines and dependencies are softer targets than production — harden where attackers actually go." },
      { Icon: FileCheck, title: "Know what's in your build", desc: "SBOMs and provenance give you a verifiable inventory of every component you ship." },
      { Icon: KeyRound, title: "Contain secrets", desc: "Proper secrets management stops leaked tokens from becoming a breach." },
      { Icon: Search, title: "Catch vulnerable deps", desc: "Automated scanning flags and helps remediate vulnerable dependencies before release." },
      { Icon: Lock, title: "Tamper-evident artifacts", desc: "Signed, verified images and artifacts so you ship only what you built." },
      { Icon: Scale, title: "Practical, not paralysing", desc: "Controls that fit your delivery flow instead of stopping it." },
    ],
    useCasesHeading: "What we secure",
    useCases: [
      { Icon: Boxes, title: "Dependency hardening", desc: "Scanning, pinning, and policy for your open-source dependencies." },
      { Icon: Workflow, title: "CI/CD hardening", desc: "Least-privilege runners, isolated builds, and protected pipelines." },
      { Icon: Lock, title: "Artifact & image signing", desc: "Sign and verify build outputs so nothing tampered ships." },
      { Icon: FileCheck, title: "SBOM & provenance", desc: "Generate software bills of materials and build provenance automatically." },
      { Icon: KeyRound, title: "Secrets management", desc: "Centralised, least-privilege secrets across environments and pipelines." },
      { Icon: Eye, title: "Continuous scanning", desc: "Automated vulnerability and secret scanning on every change." },
    ],
    tech: [
      { name: "GitHub Actions", sub: "Secure CI" },
      { name: "Trivy", sub: "Scanning" },
      { name: "Snyk", sub: "Dep scanning" },
      { name: "Sigstore", sub: "Signing" },
      { name: "SBOM", sub: "Inventory" },
      { name: "AWS IAM", sub: "Least priv." },
      { name: "Vault", sub: "Secrets" },
      { name: "Docker", sub: "Images" },
    ],
    why: [
      "We secure supply chains from the inside out because we live in CI/CD pipelines — ShiftERP ships through GitHub Actions into AWS, and every product we run has a build pipeline we harden. We know where the real weak points are because we work in them daily.",
      "Practical, layered security from senior engineers who ship — not box-ticking. 11+ products in production.",
    ],
    faqs: [
      { q: "Why is the supply chain such a target?", a: "Compromising a dependency or a CI/CD pipeline is often far easier than breaching hardened production — and one compromised build can reach every customer. It's high leverage for attackers, which is why it needs defending." },
      { q: "What's an SBOM and do we need one?", a: "A Software Bill of Materials is a verifiable inventory of every component in your software. It's increasingly expected (and sometimes required) and is the foundation for knowing your exposure when a new vulnerability drops." },
      { q: "Will this slow our releases down?", a: "Done right, no. We integrate controls into your existing pipeline as automated checks — security that runs continuously rather than as a manual gate." },
      { q: "Can you work with our current CI/CD?", a: "Yes — we harden GitHub Actions, GitLab CI, and other pipelines in place, adding least-privilege, scanning, signing, and secrets management." },
      { q: "How do you handle secrets?", a: "Centralised secrets management with least-privilege access and rotation, so a leaked token isn't a catastrophe and credentials never live in code." },
      { q: "Is this the same as a penetration test?", a: "No — it's complementary. Pen testing probes your running application; supply chain security hardens how that application is built and delivered." },
    ],
  },

  // 5 — MANAGED SERVICES
  {
    slug: "managed-services",
    name: "Managed Services",
    navLabel: "Managed Services",
    pill: "Managed Cloud Services",
    headline: "Managed cloud operations, so your team can build instead of babysit.",
    subhead:
      "Ongoing monitoring, maintenance, scaling, security, and cost control for your cloud infrastructure — run by the senior engineers who'd build it, on a model that fits your needs.",
    accent: "from-violet-100/60 via-white to-brand-50",
    heroVariant: "capabilities",
    metaTitle: "Managed Cloud Services UK — Cloud Operations | Tackxel",
    metaDescription:
      "Managed cloud services UK: ongoing monitoring, maintenance, scaling, security and cost control for AWS infrastructure by senior engineers. Book a call.",
    keywords: [
      "managed cloud services UK",
      "managed services provider",
      "cloud managed services",
      "AWS managed services",
      "cloud operations support",
    ],
    overviewHeading: "What are managed cloud services?",
    overview: [
      "Managed cloud services mean handing the ongoing operation of your infrastructure to a team that monitors it, maintains it, scales it, secures it, and keeps its costs in check — so your engineers spend their time building product instead of babysitting servers. It's the difference between owning the outcome (reliable, secure, affordable infrastructure) and owning the 2 a.m. pager.",
      "We provide managed services for the cloud platforms we build and others: proactive monitoring and alerting, patching and maintenance, scaling and performance tuning, security and backups, incident response, and continuous cost optimisation. You get a senior team that already understands production systems, on an engagement model that fits — from light-touch oversight to full operations.",
      "Because the people managing your infrastructure are the same calibre who'd architect it, you're not handing the keys to a junior NOC reading a runbook. You get engineers who can actually fix the hard problems and improve the platform over time, not just acknowledge alerts.",
    ],
    process: [
      { no: "01", title: "Onboard", desc: "We learn your infrastructure, document it, and set up monitoring, alerting, and access." },
      { no: "02", title: "Stabilise", desc: "We fix the obvious reliability, security, and cost issues so the baseline is solid." },
      { no: "03", title: "Operate", desc: "Proactive monitoring, patching, backups, scaling, and incident response, day to day." },
      { no: "04", title: "Optimise", desc: "Ongoing cost, performance, and reliability improvements — the platform gets better over time." },
      { no: "05", title: "Report", desc: "Clear reporting on health, spend, and incidents, so you always know where things stand." },
    ],
    benefitsHeading: "Why use managed services",
    benefits: [
      { Icon: Clock, title: "Reclaim engineer time", desc: "Your team builds product instead of patching servers and chasing alerts." },
      { Icon: ShieldCheck, title: "Reliable & secure", desc: "Proactive monitoring, patching, and backups keep your platform healthy and protected." },
      { Icon: DollarSign, title: "Lower, predictable cost", desc: "Continuous cost optimisation and a clear engagement model — no runaway bills." },
      { Icon: Activity, title: "Real incident response", desc: "Senior engineers who can actually fix issues, not just acknowledge them." },
      { Icon: Gauge, title: "Scales with you", desc: "Capacity and performance managed as your traffic grows." },
      { Icon: Target, title: "Senior, not a NOC", desc: "The people running it are the calibre who'd have built it." },
    ],
    useCasesHeading: "What we manage",
    useCases: [
      { Icon: Activity, title: "Monitoring & alerting", desc: "Proactive observability so problems are caught before users feel them." },
      { Icon: Wrench, title: "Maintenance & patching", desc: "Updates, patches, and routine upkeep handled for you." },
      { Icon: ShieldCheck, title: "Security & backups", desc: "Hardening, backups, and recovery you can rely on." },
      { Icon: Gauge, title: "Scaling & performance", desc: "Capacity tuned to demand as your load changes." },
      { Icon: DollarSign, title: "Cost optimisation", desc: "Ongoing right-sizing and waste reduction on your cloud spend." },
      { Icon: Server, title: "Incident response", desc: "On-call senior engineers who resolve, not just escalate." },
    ],
    tech: [
      { name: "AWS", sub: "Cloud" },
      { name: "CloudWatch", sub: "Monitoring" },
      { name: "Datadog", sub: "Observability" },
      { name: "Terraform", sub: "IaC" },
      { name: "Docker", sub: "Containers" },
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "PagerDuty", sub: "On-call" },
      { name: "GitHub Actions", sub: "CI/CD" },
    ],
    why: [
      "We manage what we know how to build. Our production platforms run on AWS with CloudWatch observability (PropMetrics), CloudFront delivery (MultiUnitX), and auto-scaling infrastructure (ShiftERP) — so when we operate your cloud, it's with hands-on production experience, not a generic playbook.",
      "Senior engineers on the pager, not a junior NOC. 11+ products shipped and operated.",
    ],
    faqs: [
      { q: "What does \"managed\" actually cover?", a: "Monitoring and alerting, maintenance and patching, scaling, security and backups, incident response, and continuous cost optimisation — scoped to the level you need, from oversight to full operations." },
      { q: "Do you only manage infrastructure you built?", a: "No. We onboard existing infrastructure too — documenting it, stabilising the obvious issues, then operating and improving it." },
      { q: "Who actually responds to incidents?", a: "Senior engineers who understand production systems and can fix root causes — not a first-line NOC that only escalates." },
      { q: "How is pricing structured?", a: "On an engagement model that fits your needs and scale, scoped transparently up front. We'd rather right-size the engagement than oversell it." },
      { q: "Will you help reduce our cloud bill?", a: "Yes — cost optimisation is part of the service: right-sizing, removing waste, and reporting on spend so it stays predictable." },
      { q: "Can we still control our own infrastructure?", a: "Absolutely. It's your infrastructure — we operate it transparently with infrastructure-as-code and clear reporting, and you keep full control and ownership." },
    ],
  },

  // 6 — APPLICATION MODERNIZATION
  {
    slug: "application-modernization",
    name: "Application Modernization",
    navLabel: "Application Modernization",
    pill: "Application Modernization",
    headline: "Modernize legacy systems without betting the business on a rewrite.",
    subhead:
      "Replatform, refactor, and re-architect aging applications onto modern, cloud-native foundations — incrementally, with the business running the whole time.",
    accent: "from-orange-50 via-white to-brand-50",
    heroVariant: "rag",
    metaTitle: "Application Modernization Services UK | Tackxel",
    metaDescription:
      "Application modernization UK: replatform and refactor legacy systems onto modern cloud-native foundations — incrementally, no risky big-bang rewrite. Book a call.",
    keywords: [
      "application modernization services",
      "legacy modernization UK",
      "legacy system modernization",
      "application replatforming",
      "software modernization company",
    ],
    overviewHeading: "What is application modernization?",
    overview: [
      "Application modernization is the work of bringing aging software up to date — moving it onto modern architectures, languages, and cloud-native infrastructure so it's faster, cheaper to run, more secure, and possible to change again. Legacy systems aren't bad because they're old; they're a problem when they block new features, leak risk, cost a fortune to run, or only one person understands them.",
      "We modernise incrementally, not with a big-bang rewrite that risks the whole business. Using the strangler-fig pattern, we stand up modern components alongside the legacy system and migrate functionality in slices, keeping everything running and reversible at each step. Along the way we containerise, add automated testing and CI/CD, and move to managed cloud services — so the modernised system is genuinely operable, not just rewritten.",
      "The hardest part of modernization is preserving the institutional knowledge buried in old code while shedding its constraints. We treat that with respect: understanding what the system really does before we change it, so the new version keeps what mattered and drops what didn't.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We map the legacy system, its real behaviour, dependencies, and the business value locked inside it." },
      { no: "02", title: "Strategy", desc: "Replatform, refactor, or re-architect — chosen per component, sequenced to deliver value early." },
      { no: "03", title: "Strangle", desc: "Modern components stood up alongside the legacy system; functionality migrated in safe, reversible slices." },
      { no: "04", title: "Harden", desc: "Containers, automated testing, CI/CD, and cloud-native infrastructure make the new system operable." },
      { no: "05", title: "Retire", desc: "The legacy system is decommissioned only once the modern one fully owns its responsibilities." },
    ],
    benefitsHeading: "Why modernize",
    benefits: [
      { Icon: Zap, title: "Ship features again", desc: "Unblock a roadmap that legacy constraints have been stalling for quarters." },
      { Icon: DollarSign, title: "Cut running costs", desc: "Modern, cloud-native infrastructure is usually far cheaper to operate than legacy estates." },
      { Icon: ShieldCheck, title: "Close security gaps", desc: "Retire unsupported frameworks and platforms that quietly accumulate risk." },
      { Icon: Repeat, title: "No big-bang risk", desc: "Incremental, reversible migration keeps the business running throughout." },
      { Icon: Wrench, title: "Maintainable again", desc: "Code and infrastructure your current team can actually understand and change." },
      { Icon: Gauge, title: "Ready to scale", desc: "Modern foundations that handle growth instead of buckling under it." },
    ],
    useCasesHeading: "What we modernize",
    useCases: [
      { Icon: ArrowRightLeft, title: "Replatforming", desc: "Move apps onto modern runtimes and cloud infrastructure with minimal change." },
      { Icon: Boxes, title: "Monolith decomposition", desc: "Carve a monolith into services where it actually helps — not for its own sake." },
      { Icon: RefreshCw, title: "Framework upgrades", desc: "Move off unsupported, end-of-life frameworks and languages." },
      { Icon: Container, title: "Containerisation", desc: "Package legacy apps to run on modern, portable infrastructure." },
      { Icon: Database, title: "Data migration", desc: "Move and modernise data stores safely, without losing history." },
      { Icon: Cloud, title: "Cloud re-platforming", desc: "Bring on-prem or dated cloud setups onto modern managed services." },
    ],
    tech: [
      { name: "AWS", sub: "Cloud" },
      { name: "Docker", sub: "Containers" },
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "Terraform", sub: "IaC" },
      { name: "Next.js", sub: "Web" },
      { name: "Node.js", sub: "Services" },
      { name: "PostgreSQL", sub: "Data" },
      { name: "GitHub Actions", sub: "CI/CD" },
    ],
    why: [
      "We build modern, cloud-native systems from scratch every day — auto-scaling AWS platforms with containers, managed databases, and CI/CD (ShiftERP, PropMetrics, MultiUnitX, LuxeLocker). That's the target state we move legacy systems toward, and we know how to land it incrementally.",
      "We respect what legacy systems got right and modernise without betting the business on a rewrite. Senior engineers, 11+ products shipped.",
    ],
    faqs: [
      { q: "Do you do full rewrites?", a: "Rarely, and only when truly warranted. Big-bang rewrites are high-risk; we prefer incremental modernization (the strangler-fig pattern) that keeps the business running and stays reversible." },
      { q: "Will our system keep running during modernization?", a: "Yes. We migrate functionality in slices alongside the existing system, so it stays live throughout and each step can be rolled back." },
      { q: "What if nobody understands the legacy code?", a: "That's common. Part of our process is understanding what the system actually does — its real behaviour and the business value inside it — before we change anything." },
      { q: "How do you decide replatform vs refactor vs rewrite?", a: "Per component, on cost, risk, and value. Some parts just need replatforming; others warrant refactoring; a few are best replaced. We sequence for early value." },
      { q: "Will modernization reduce our costs?", a: "Usually significantly — modern cloud-native infrastructure is typically far cheaper to run than legacy estates, and easier to maintain." },
      { q: "Can you modernise the data layer too?", a: "Yes — data migration and modernisation are part of the work, done carefully so you don't lose history or integrity." },
    ],
  },

  // 7 — CLOUD MIGRATION
  {
    slug: "cloud-migration",
    name: "Cloud Migration",
    navLabel: "Cloud Migration",
    pill: "Cloud Migration",
    headline: "Move to AWS, GCP, or Azure — without the horror stories.",
    subhead:
      "Plan and execute your cloud migration in safe, reversible slices. Lift-and-shift or refactor-and-optimise, sequenced to cut risk and cost, delivered by engineers who run cloud in production.",
    accent: "from-sky-50 via-white to-brand-50",
    heroVariant: "neural",
    metaTitle: "Cloud Migration Services UK — AWS, GCP, Azure | Tackxel",
    metaDescription:
      "Cloud migration services UK: move to AWS, GCP or Azure in safe, reversible slices — lift-and-shift or refactor — by senior engineers who run cloud. Book a call.",
    keywords: [
      "cloud migration services",
      "cloud migration company UK",
      "AWS migration services",
      "cloud migration consulting",
      "migrate to cloud",
    ],
    overviewHeading: "What is cloud migration?",
    overview: [
      "Cloud migration is moving your applications, data, and infrastructure from where they live now — on-premises, a data centre, or a dated cloud setup — onto a modern cloud platform like AWS, GCP, or Azure. Done well, it cuts running costs, improves reliability and scale, and unlocks managed services. Done badly, it's a byword for blown budgets and broken systems — which is why how you migrate matters as much as where you migrate to.",
      "We plan and execute migrations in safe, reversible slices rather than one terrifying cutover. We start with an assessment and a migration plan that picks the right approach per workload — lift-and-shift where speed matters, refactor-and-optimise where the cloud's strengths pay off — then move workloads incrementally with rollback paths, validating each step. Infrastructure-as-code, automated pipelines, and observability come along for the ride, so you land on solid foundations.",
      "Because we operate cloud platforms in production, we migrate toward something we know how to run — not just a successful copy-paste, but a platform that's reliable, cost-controlled, and operable once you're there.",
    ],
    process: [
      { no: "01", title: "Assess", desc: "We inventory your workloads, dependencies, and data, and assess each for the right migration path." },
      { no: "02", title: "Plan", desc: "A migration plan: approach per workload (rehost, replatform, refactor), sequencing, and rollback strategy." },
      { no: "03", title: "Prepare", desc: "Landing zone, networking, security, and infrastructure-as-code set up before anything moves." },
      { no: "04", title: "Migrate", desc: "Workloads and data moved in slices with validation and rollback — no single big-bang cutover." },
      { no: "05", title: "Optimise", desc: "Right-sizing, cost tuning, and observability so the new platform is cheaper and more reliable." },
    ],
    benefitsHeading: "Why migrate to the cloud",
    benefits: [
      { Icon: DollarSign, title: "Cut running costs", desc: "Right-sized, pay-for-use cloud infrastructure is usually cheaper than fixed on-prem capacity." },
      { Icon: Gauge, title: "Scale on demand", desc: "Handle spikes and growth without buying hardware ahead of need." },
      { Icon: ShieldCheck, title: "Better reliability", desc: "Multi-AZ infrastructure and managed services raise your baseline uptime." },
      { Icon: Repeat, title: "Reversible by slices", desc: "Incremental migration with rollback means no all-or-nothing risk." },
      { Icon: Wrench, title: "Less to maintain", desc: "Managed services offload patching, backups, and hardware from your team." },
      { Icon: Globe, title: "Reach & resilience", desc: "Deploy closer to users and across regions for speed and disaster recovery." },
    ],
    useCasesHeading: "How we migrate",
    useCases: [
      { Icon: ArrowRightLeft, title: "Lift-and-shift (rehost)", desc: "Move workloads to the cloud quickly when speed is the priority." },
      { Icon: Container, title: "Replatform", desc: "Containerise and adopt managed services as you move, for better economics." },
      { Icon: RefreshCw, title: "Refactor-and-optimise", desc: "Re-architect the workloads where the cloud's strengths really pay off." },
      { Icon: Database, title: "Data migration", desc: "Move databases and storage safely, with integrity and minimal downtime." },
      { Icon: Layers, title: "Landing zone setup", desc: "Secure, well-architected cloud foundations before workloads arrive." },
      { Icon: DollarSign, title: "Post-migration FinOps", desc: "Right-sizing and cost optimisation once you're running in the cloud." },
    ],
    tech: [
      { name: "AWS", sub: "EC2/S3/RDS" },
      { name: "GCP", sub: "Cloud" },
      { name: "Azure", sub: "Cloud" },
      { name: "Terraform", sub: "IaC" },
      { name: "Docker", sub: "Containers" },
      { name: "Kubernetes", sub: "Orchestration" },
      { name: "GitHub Actions", sub: "CI/CD" },
      { name: "CloudWatch", sub: "Observability" },
    ],
    why: [
      "We migrate toward platforms we operate in production. Our shipped systems run on AWS — EC2, S3, RDS, ECS, ALB, Auto Scaling, CloudFront, CloudWatch — across LuxeLocker, PropMetrics, MultiUnitX, and ShiftERP. So we move you to a destination we know how to make reliable and cost-controlled.",
      "Safe, sliced migrations from senior engineers — no horror-story cutovers. 11+ products shipped and running.",
    ],
    faqs: [
      { q: "Lift-and-shift or refactor — which is right?", a: "It depends per workload. Lift-and-shift is fastest; refactoring unlocks the cloud's cost and scale benefits. We choose per workload and sequence so you get value early without unnecessary risk." },
      { q: "Will there be downtime?", a: "We migrate in slices with validation and rollback, minimising or avoiding downtime. Data migrations are planned specifically to protect integrity and uptime." },
      { q: "AWS, GCP, or Azure?", a: "Whichever fits your workloads, team, and commercial situation. Most of our production experience is on AWS, but we'll recommend and execute the right destination for you." },
      { q: "What if the migration goes wrong?", a: "Each slice has a rollback path, and we validate before committing. That's the whole point of incremental migration — no single step can sink you." },
      { q: "Will the cloud actually be cheaper?", a: "Usually, with discipline — right-sizing and FinOps after migration are part of our process. Without that discipline cloud can cost more, which is exactly why we build it in." },
      { q: "Can you migrate our databases?", a: "Yes — database and storage migration are core to the work, executed carefully to preserve integrity and minimise downtime." },
    ],
  },
];

export function getCloudService(slug: string): AiService | undefined {
  return cloudServices.find((s) => s.slug === slug);
}

export const cloudServiceSlugs = cloudServices.map((s) => s.slug);
